-- Korean Stats/Skills wording is no longer maintained in Lua.
-- Canonical sources:
--   Data/Text localization/KO_GlobalTxt.txt
--   Data/Text localization/KO_StatsDescriptions.tsv
--   Data/Text localization/KO_Skilldes.txt
-- Runtime projection:
--   Data/Text localization/KO_StatsSkillsRuntime.txt
-- LocalizeTables.lua applies the generated projection during initialization
-- and TxtFilesReloaded, preserving the late-reapply behavior without duplicate
-- translation ownership.
